### ISSUE TITLE
fix contact form

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/ESCAIDE_2019_workshop#1]
Current contact form does not work. Would be nice to fix it, but beyond my skills. @amygimma could you take a look? :)

**Comment by amygimma** [comment]
@thibautjombart -  since Hugo is a static site builder, it doesn't support contact forms out of the box. 

I think the simplest solution will be to use [formspree](https://formspree.io/) which can handle up to 1000 messages for $12/month with some protection against spammers/bots and options for redirecting or other user feedback. The forms will all take on the css styling of the Hugo site.

We could also use [formspree](https://github.com/formspree/formspree#running-on-heroku) and host on [heroku](https://www.heroku.com/pricing) which will direct the messages to an email, but this won't come with the benefits of the paid version of formspree and might have some performance issues (free, $7, $25/month options). 

Which is the best option? also we will need to either set up an email or have the messages come through to one of our emails - how do you want that to work?

**Comment by thibautjombart** [comment]
I think we can do without a form then. We could probably expense this but that is going to be more hassle than is worth it. Could you try to remove the form from the page and maybe PR or push the change?

**Comment by thibautjombart** [comment]
ps: thanks for looking into this! :)

**Comment by amygimma** [comment]
no prob, will do!

**Comment by amygimma** [comment]
just realized we're hosting on [netflify](https://www.netlify.com/pricing/) so there's another option if we decide to add it - still about $19/month

**Comment by thibautjombart** [comment]
Yep, but still best spend nothing on this :)
